import { SCORM_EXPORT_RUNTIME_PLAYER_FILES, SCORM_EXPORT_RUNTIME_VERSION } from "./runtime-assets";

import type {
  ScormExportCourseJson,
  ScormExportImportedScormLessonSnapshot,
  ScormExportPackageFile,
} from "./types";

const SCORM_EXPORT_COURSE_DATA_PATH = "data/course.json";

export type RenderScormExportManifestInput = {
  courseJson: ScormExportCourseJson;
  files?: ScormExportPackageFile[];
};

export function renderScormExportManifest({
  courseJson,
  files = [],
}: RenderScormExportManifestInput) {
  const packageFiles = uniqueManifestFiles([
    SCORM_EXPORT_COURSE_DATA_PATH,
    ...SCORM_EXPORT_RUNTIME_PLAYER_FILES,
    ...files.map((file) => file.path),
  ]);

  return `<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="mentingo-${escapeXml(courseJson.course.id)}" version="1.0" xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2" xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>1.2</schemaversion>
  </metadata>
  <organizations default="mentingo-course">
    <organization identifier="mentingo-course">
      <title>${escapeXml(courseJson.course.title)}</title>
${renderOrganizationItems(courseJson)}
    </organization>
  </organizations>
  <resources>
${renderLessonResources(courseJson, packageFiles)}
  </resources>
  <!-- Generated by Mentingo SCORM export runtime ${escapeXml(SCORM_EXPORT_RUNTIME_VERSION)} -->
</manifest>
`;
}

function renderOrganizationItems(courseJson: ScormExportCourseJson) {
  return courseJson.chapters
    .map((chapter) => {
      const lessonItems = chapter.lessonIds
        .map((lessonId) => courseJson.lessons[lessonId])
        .filter(Boolean)
        .map((lesson) => {
          if (lesson.type === "scorm") {
            return renderImportedScormLessonItem(lesson);
          }

          return `        <item identifier="${itemIdentifier(lesson.id)}" identifierref="${resourceIdentifier(lesson.id)}">
          <title>${escapeXml(lesson.title)}</title>
        </item>`;
        })
        .join("\n");

      return `      <item identifier="${chapterIdentifier(chapter.id)}">
        <title>${escapeXml(chapter.title)}</title>
${lessonItems}
      </item>`;
    })
    .join("\n");
}

function renderImportedScormLessonItem(lesson: ScormExportImportedScormLessonSnapshot) {
  const scoItems = lesson.scos
    .map(
      (
        sco,
      ) => `          <item identifier="${importedScoItemIdentifier(lesson.id, sco.id)}" identifierref="${importedScoResourceIdentifier(lesson.id, sco.id)}">
            <title>${escapeXml(sco.title)}</title>
          </item>`,
    )
    .join("\n");

  return `        <item identifier="${itemIdentifier(lesson.id)}">
          <title>${escapeXml(lesson.title)}</title>
${scoItems}
        </item>`;
}

function renderLessonResources(courseJson: ScormExportCourseJson, packageFiles: string[]) {
  return [
    ...orderedLessons(courseJson)
      .filter((lesson) => lesson.type !== "scorm")
      .map((lesson) => {
        const launchHref = lessonLaunchPath(lesson.id);
        const fileEntries = packageFiles
          .map((filePath) => `      <file href="${escapeXml(filePath)}" />`)
          .join("\n");

        return `    <resource identifier="${resourceIdentifier(lesson.id)}" type="webcontent" adlcp:scormtype="sco" href="${escapeXml(launchHref)}">
${fileEntries}
    </resource>`;
      }),
    ...orderedLessons(courseJson)
      .filter((lesson): lesson is ScormExportImportedScormLessonSnapshot => lesson.type === "scorm")
      .flatMap((lesson) =>
        lesson.scos.map((sco) => {
          const launchHref = importedScormPackagePath(lesson.packageId, sco.launchPath);
          const resourceFiles = importedScoResourceFiles(lesson.packageId, sco.files, packageFiles);
          const fileEntries = resourceFiles
            .map((filePath) => `      <file href="${escapeXml(filePath)}" />`)
            .join("\n");

          return `    <resource identifier="${importedScoResourceIdentifier(lesson.id, sco.id)}" type="webcontent" adlcp:scormtype="sco" href="${escapeXml(launchHref)}">
${fileEntries}
    </resource>`;
        }),
      ),
  ].join("\n");
}

function orderedLessons(courseJson: ScormExportCourseJson) {
  return courseJson.chapters.flatMap((chapter) =>
    chapter.lessonIds.map((lessonId) => courseJson.lessons[lessonId]).filter(Boolean),
  );
}

function uniqueManifestFiles(filePaths: string[]) {
  return Array.from(new Set(filePaths)).filter(Boolean);
}

function chapterIdentifier(chapterId: string) {
  return `chapter-${sanitizeIdentifier(chapterId)}`;
}

function itemIdentifier(lessonId: string) {
  return `item-${sanitizeIdentifier(lessonId)}`;
}

function resourceIdentifier(lessonId: string) {
  return `resource-${sanitizeIdentifier(lessonId)}`;
}

export function lessonLaunchPath(lessonId: string) {
  return `player/launch/${sanitizeIdentifier(lessonId)}.html`;
}

export function importedScormPackagePath(packageId: string, relativePath: string) {
  const { path, suffix } = splitPathSuffix(relativePath);
  return `assets/imported-scorm/${sanitizeIdentifier(packageId)}/${normalizePackagePath(path)}${suffix}`;
}

function importedScoItemIdentifier(lessonId: string, scoId: string) {
  return `scorm-sco-item-${sanitizeIdentifier(lessonId)}-${sanitizeIdentifier(scoId)}`;
}

function importedScoResourceIdentifier(lessonId: string, scoId: string) {
  return `scorm-sco-resource-${sanitizeIdentifier(lessonId)}-${sanitizeIdentifier(scoId)}`;
}

function importedScoResourceFiles(packageId: string, files: string[], packageFiles: string[]) {
  const explicitFiles = files.map((file) => importedScormPackagePath(packageId, file));
  if (explicitFiles.length) return uniqueManifestFiles(explicitFiles);

  const importedPackagePrefix = `assets/imported-scorm/${sanitizeIdentifier(packageId)}/`;
  return packageFiles.filter((filePath) => filePath.startsWith(importedPackagePrefix));
}

function splitPathSuffix(value: string) {
  const suffixIndex = value.search(/[?#]/);
  if (suffixIndex === -1) return { path: value, suffix: "" };

  return {
    path: value.slice(0, suffixIndex),
    suffix: value.slice(suffixIndex),
  };
}

function normalizePackagePath(value: string) {
  return value.replace(/\\/g, "/").replace(/^\/+/, "");
}

function sanitizeIdentifier(value: string) {
  return value.replace(/[^A-Za-z0-9_.-]/g, "-");
}

function escapeXml(value: string) {
  return value.replace(/[<>&'"]/g, (character) => {
    switch (character) {
      case "<":
        return "&lt;";
      case ">":
        return "&gt;";
      case "&":
        return "&amp;";
      case "'":
        return "&apos;";
      case '"':
        return "&quot;";
      default:
        return character;
    }
  });
}
