services:
  project-db:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: guidebook
      POSTGRES_DB: guidebook
    volumes:
      - lms-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10

  redis:
    image: redis:8.0-M02-alpine3.20
    restart: always
    ports:
      - 6379:6379
    healthcheck:
          test: [ "CMD", "redis-cli", "ping" ]
          interval: 3s
          timeout: 3s
          retries: 10
    volumes:
      - lms-redis-data:/data
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  lms-db-data:
    driver: local
  lms-redis-data:
    driver: local

