export const RATE_LIMIT_WINDOW_SEC = 60;

export const RATE_LIMITS = {
  AUTH_SENSITIVE_ENDPOINTS_REQUESTS_PER_MINUTE: 5,
  AUTH_STANDARD_ENDPOINTS_REQUESTS_PER_MINUTE: 10,
  INTEGRATION_READ_REQUESTS_PER_MINUTE: 120,
  INTEGRATION_WRITE_REQUESTS_PER_MINUTE: 30,
  GENERAL_GET_REQUESTS_PER_MINUTE: 240,
  GENERAL_WRITE_REQUESTS_PER_MINUTE: 60,
} as const;
