export {
  AI_JUDGE_DRAFT_CHANGE_TYPE,
  AI_JUDGE_DRAFT_CHANGE_FIELD,
  AI_JUDGE_GENERATION_MAX_ATTEMPTS,
  AI_JUDGE_GENERATION_MODE,
  AI_JUDGE_GENERATION_STATUS,
  AI_JUDGE_VALIDATION_SEVERITY,
  AI_JUDGE_VALIDATION_TARGET,
} from "@repo/shared";

export type { AiJudgeGenerationMode } from "@repo/shared";

export const AI_JUDGE_CRITERION_REF_PATTERN = "^C[1-9][0-9]*$";
export const AI_JUDGE_BLOCKING_ERROR_REF_PATTERN = "^B[1-9][0-9]*$";
