import { ACTIVITY_LOG_ACTION_TYPES, AUTOMATION_STATUSES } from "@repo/shared";

export const AUTOMATION_LIFECYCLE_OPERATIONS = {
  APPLY: "apply",
  ENABLE: "enable",
  DISABLE: "disable",
  ARCHIVE: "archive",
} as const;

export const AUTOMATION_LIFECYCLE_TARGET_STATUSES = {
  [AUTOMATION_LIFECYCLE_OPERATIONS.ENABLE]: AUTOMATION_STATUSES.ENABLED,
  [AUTOMATION_LIFECYCLE_OPERATIONS.DISABLE]: AUTOMATION_STATUSES.DISABLED,
  [AUTOMATION_LIFECYCLE_OPERATIONS.ARCHIVE]: AUTOMATION_STATUSES.ARCHIVED,
} as const;

export const AUTOMATION_LIFECYCLE_ACTIVITY_TYPES = {
  [AUTOMATION_LIFECYCLE_OPERATIONS.APPLY]: ACTIVITY_LOG_ACTION_TYPES.APPLY_AUTOMATION,
  [AUTOMATION_LIFECYCLE_OPERATIONS.ENABLE]: ACTIVITY_LOG_ACTION_TYPES.ENABLE_AUTOMATION,
  [AUTOMATION_LIFECYCLE_OPERATIONS.DISABLE]: ACTIVITY_LOG_ACTION_TYPES.DISABLE_AUTOMATION,
  [AUTOMATION_LIFECYCLE_OPERATIONS.ARCHIVE]: ACTIVITY_LOG_ACTION_TYPES.ARCHIVE_AUTOMATION,
} as const;

export const AUTOMATION_RUNTIME = Symbol("AUTOMATION_RUNTIME");
