export const NOTIFICATIONS_HANDLES = {
  TRIGGER: "notifications-trigger",
  MOBILE_TRIGGER: "notifications-mobile-trigger",
  PAGE: "notifications-page",
  POPOVER: "notifications-popover",
  REFRESH_BUTTON: "notifications-refresh-button",
  CREATE_BUTTON: "notifications-create-button",
  LOAD_MORE_BUTTON: "notifications-load-more-button",
  CENTER_LINK: "notifications-center-link",
  MARK_ALL_READ_BUTTON: "notifications-mark-all-read-button",
  EMPTY_STATE: "notifications-empty-state",
  CREATE_DIALOG: "notifications-create-dialog",
  CREATE_LANGUAGE_SELECT: "notifications-create-language-select",
  CREATE_TITLE_INPUT: "notifications-create-title-input",
  CREATE_CONTENT_INPUT: "notifications-create-content-input",
  CREATE_GROUP_SELECT: "notifications-create-group-select",
  CREATE_SUBMIT_BUTTON: "notifications-create-submit-button",
  DELETE_CONFIRM_BUTTON: "notifications-delete-confirm-button",
  card: (announcementId: string) => `notification-announcement-card-${announcementId}`,
  deleteButton: (announcementId: string) => `notification-announcement-delete-${announcementId}`,
  languageOption: (language: string) => `notifications-create-language-option-${language}`,
  groupOption: (groupId: string) => `notifications-create-group-option-${groupId}`,
  markReadButton: (announcementId: string) => `notification-announcement-read-${announcementId}`,
} as const;
