export const ENCRYPTION_ALG = "aes-256-gcm";
export const ALLOWED_SECRETS = [
  "MICROSOFT_CLIENT_ID",
  "MICROSOFT_CLIENT_SECRET",
  "MICROSOFT_OAUTH_ENABLED",
  "OPENAI_API_KEY",
  "BUNNY_STREAM_API_KEY",
  "BUNNY_STREAM_SIGNING_KEY",
  "BUNNY_STREAM_LIBRARY_ID",
  "BUNNY_STREAM_CDN_URL",
  "GOOGLE_CLIENT_ID",
  "GOOGLE_CLIENT_SECRET",
  "GOOGLE_OAUTH_ENABLED",
  "VITE_GOOGLE_OAUTH_ENABLED",
  "VITE_MICROSOFT_OAUTH_ENABLED",
];
