export const CERTIFICATE_EXPIRATION_UPDATE_BATCH_SIZE = 100;
export const CERTIFICATE_PROGRESS_RESET_BATCH_SIZE = 25;
export const CERTIFICATE_ACTIVITY_LOG_BATCH_SIZE = 100;
export const CERTIFICATE_EMAIL_BATCH_SIZE = 50;
