#!/bin/bash
set -e

LANGFUSE_DB=${LANGFUSE_DB:-langfuse_db}
LANGFUSE_USER=${LANGFUSE_USER:-langfuse_user}
LANGFUSE_PASS=${LANGFUSE_PASS:-lf_strong_pass}


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-SQL
  CREATE DATABASE ${LANGFUSE_DB};
  CREATE USER ${LANGFUSE_USER} WITH ENCRYPTED PASSWORD '${LANGFUSE_PASS}';
  GRANT ALL PRIVILEGES ON DATABASE ${LANGFUSE_DB} TO ${LANGFUSE_USER};
SQL