export const REDIS_CLIENT = Symbol("REDIS_CLIENT");
export const REDIS_PUBLISHER_CLIENT = Symbol("REDIS_PUBLISHER_CLIENT");
export const REDIS_SUBSCRIBER_CLIENT = Symbol("REDIS_SUBSCRIBER_CLIENT");
export const REDIS_EVENTS_SUBSCRIBER_CLIENT = Symbol("REDIS_EVENTS_SUBSCRIBER_CLIENT");
