export const ANNOUNCEMENT_SCHEDULE_STEP_MINUTES = 5;
export const ANNOUNCEMENT_SCHEDULE_STEP_MS = ANNOUNCEMENT_SCHEDULE_STEP_MINUTES * 60 * 1000;
export const SCHEDULED_ANNOUNCEMENT_PUBLISH_BATCH_SIZE = 100;
