CREATE INDEX IF NOT EXISTS "activity_logs_tenant_id_idx" ON "activity_logs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_mentor_lessons_tenant_id_idx" ON "ai_mentor_lessons" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_mentor_student_lesson_progress_tenant_id_idx" ON "ai_mentor_student_lesson_progress" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_mentor_thread_messages_tenant_id_idx" ON "ai_mentor_thread_messages" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_mentor_threads_tenant_id_idx" ON "ai_mentor_threads" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "announcements_tenant_id_idx" ON "announcements" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "article_sections_tenant_id_idx" ON "article_sections" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "articles_tenant_id_idx" ON "articles" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "categories_tenant_id_idx" ON "categories" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "certificates_tenant_id_idx" ON "certificates" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chapters_tenant_id_idx" ON "chapters" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "course_slugs_tenant_id_idx" ON "course_slugs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "course_students_stats_tenant_id_idx" ON "course_students_stats" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "courses_tenant_id_idx" ON "courses" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "courses_summary_stats_tenant_id_idx" ON "courses_summary_stats" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "create_tokens_tenant_id_idx" ON "create_tokens" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "credentials_tenant_id_idx" ON "credentials" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "doc_chunks_tenant_id_idx" ON "doc_chunks" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_to_ai_mentor_lesson_tenant_id_idx" ON "document_to_ai_mentor_lesson" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "documents_tenant_id_idx" ON "documents" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "group_announcements_tenant_id_idx" ON "group_announcements" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "group_courses_tenant_id_idx" ON "group_courses" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "group_users_tenant_id_idx" ON "group_users" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "groups_tenant_id_idx" ON "groups" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lesson_learning_time_tenant_id_idx" ON "lesson_learning_time" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lessons_tenant_id_idx" ON "lessons" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "news_tenant_id_idx" ON "news" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "question_answer_options_tenant_id_idx" ON "question_answer_options" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "questions_tenant_id_idx" ON "questions" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "questions_and_answers_tenant_id_idx" ON "questions_and_answers" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "quiz_attempts_tenant_id_idx" ON "quiz_attempts" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "reset_tokens_tenant_id_idx" ON "reset_tokens" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "resource_entity_tenant_id_idx" ON "resource_entity" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "resources_tenant_id_idx" ON "resources" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scorm_files_tenant_id_idx" ON "scorm_files" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scorm_metadata_tenant_id_idx" ON "scorm_metadata" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "secrets_tenant_id_idx" ON "secrets" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "settings_tenant_id_idx" ON "settings" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student_chapter_progress_tenant_id_idx" ON "student_chapter_progress" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student_courses_tenant_id_idx" ON "student_courses" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student_lesson_progress_tenant_id_idx" ON "student_lesson_progress" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student_question_answers_tenant_id_idx" ON "student_question_answers" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_announcements_tenant_id_idx" ON "user_announcements" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_details_tenant_id_idx" ON "user_details" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_onboarding_tenant_id_idx" ON "user_onboarding" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_statistics_tenant_id_idx" ON "user_statistics" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "users_tenant_id_idx" ON "users" USING btree ("tenant_id");