export const LIVEKIT_DEFAULT_ROOM_EMPTY_TIMEOUT_SECONDS = 6 * 60 * 60;
export const LIVEKIT_DEFAULT_ROOM_DEPARTURE_TIMEOUT_SECONDS = 60 * 60;
export const LIVEKIT_DEFAULT_TOKEN_TTL_SECONDS = 6 * 60 * 60;
