export const VIDEO_COMPLETION_COVERAGE_THRESHOLD = 0.9;
export const VIDEO_TRACKING_BUCKET_SIZE_SECONDS = 1;
export const VIDEO_TRACKING_FLUSH_INTERVAL_SECONDS = 15;
export const VIDEO_TRACKING_FIRST_FLUSH_MAX_SECONDS = 20;
export const MAX_VIDEO_TRACKING_PLAYBACK_RATE = 2;
export const VIDEO_TRACKING_TOLERANCE_SECONDS = 3;
export const VIDEO_WATCH_SESSION_TTL_SECONDS = 2 * 60 * 60;
