import { DASHBOARD_WIDGET_IDS, DASHBOARD_WIDGET_SIZES, PERMISSIONS } from "@repo/shared";

import type { DashboardWidgetDefinition } from "../dashboard.types";
import type { DashboardWidgetId } from "@repo/shared";

export const DASHBOARD_WIDGET_DEFINITIONS: Record<DashboardWidgetId, DashboardWidgetDefinition> = {
  [DASHBOARD_WIDGET_IDS.TRAINING_COMPLETION]: {
    id: DASHBOARD_WIDGET_IDS.TRAINING_COMPLETION,
    defaultSize: DASHBOARD_WIDGET_SIZES.MEDIUM,
    requiredPermissions: [PERMISSIONS.STATISTICS_READ],
  },
  [DASHBOARD_WIDGET_IDS.DEADLINE_RISKS]: {
    id: DASHBOARD_WIDGET_IDS.DEADLINE_RISKS,
    defaultSize: DASHBOARD_WIDGET_SIZES.SMALL,
    requiredPermissions: [PERMISSIONS.STATISTICS_READ],
  },
  [DASHBOARD_WIDGET_IDS.INCOMPLETE_COURSES]: {
    id: DASHBOARD_WIDGET_IDS.INCOMPLETE_COURSES,
    defaultSize: DASHBOARD_WIDGET_SIZES.MEDIUM,
    requiredPermissions: [PERMISSIONS.STATISTICS_READ],
  },
  [DASHBOARD_WIDGET_IDS.EVENT_CALENDAR]: {
    id: DASHBOARD_WIDGET_IDS.EVENT_CALENDAR,
    defaultSize: DASHBOARD_WIDGET_SIZES.LARGE,
    requiredPermissions: [PERMISSIONS.CALENDAR_READ],
  },
  [DASHBOARD_WIDGET_IDS.CONTINUE_LEARNING]: {
    id: DASHBOARD_WIDGET_IDS.CONTINUE_LEARNING,
    defaultSize: DASHBOARD_WIDGET_SIZES.LARGE,
    requiredPermissions: [PERMISSIONS.COURSE_READ_ASSIGNED],
  },
  [DASHBOARD_WIDGET_IDS.REQUIRED_COURSE]: {
    id: DASHBOARD_WIDGET_IDS.REQUIRED_COURSE,
    defaultSize: DASHBOARD_WIDGET_SIZES.MEDIUM,
    requiredPermissions: [PERMISSIONS.COURSE_READ_ASSIGNED],
  },
  [DASHBOARD_WIDGET_IDS.COURSE_COMPLETION]: {
    id: DASHBOARD_WIDGET_IDS.COURSE_COMPLETION,
    defaultSize: DASHBOARD_WIDGET_SIZES.SMALL,
    requiredPermissions: [PERMISSIONS.STATISTICS_READ_SELF],
  },
  [DASHBOARD_WIDGET_IDS.CERTIFICATES]: {
    id: DASHBOARD_WIDGET_IDS.CERTIFICATES,
    defaultSize: DASHBOARD_WIDGET_SIZES.SMALL,
    requiredPermissions: [PERMISSIONS.CERTIFICATE_READ],
  },
  [DASHBOARD_WIDGET_IDS.AI_MENTOR_PRACTICE]: {
    id: DASHBOARD_WIDGET_IDS.AI_MENTOR_PRACTICE,
    defaultSize: DASHBOARD_WIDGET_SIZES.MEDIUM,
    requiredPermissions: [PERMISSIONS.AI_USE],
  },
};
