import { DASHBOARD_WIDGET_IDS, DASHBOARD_WIDGET_SIZES, SYSTEM_ROLE_SLUGS } from "@repo/shared";

import type { DashboardLayoutWidget } from "../dashboard.types";
import type { SystemRoleSlug } from "@repo/shared";

const widget = (
  widgetId: DashboardLayoutWidget["widgetId"],
  order: number,
  size: DashboardLayoutWidget["size"],
  settings: Record<string, unknown> = {},
): DashboardLayoutWidget => ({ widgetId, order, enabled: true, size, settings });

export const ADMIN_DEFAULT_LAYOUT: DashboardLayoutWidget[] = [
  widget(DASHBOARD_WIDGET_IDS.TRAINING_COMPLETION, 1, DASHBOARD_WIDGET_SIZES.MEDIUM),
  widget(DASHBOARD_WIDGET_IDS.DEADLINE_RISKS, 2, DASHBOARD_WIDGET_SIZES.SMALL, {
    deadlineWindowDays: 7,
  }),
  widget(DASHBOARD_WIDGET_IDS.INCOMPLETE_COURSES, 3, DASHBOARD_WIDGET_SIZES.MEDIUM),
  widget(DASHBOARD_WIDGET_IDS.EVENT_CALENDAR, 4, DASHBOARD_WIDGET_SIZES.LARGE),
];

export const STUDENT_DEFAULT_LAYOUT: DashboardLayoutWidget[] = [
  widget(DASHBOARD_WIDGET_IDS.CONTINUE_LEARNING, 1, DASHBOARD_WIDGET_SIZES.LARGE),
  widget(DASHBOARD_WIDGET_IDS.REQUIRED_COURSE, 2, DASHBOARD_WIDGET_SIZES.MEDIUM),
  widget(DASHBOARD_WIDGET_IDS.COURSE_COMPLETION, 3, DASHBOARD_WIDGET_SIZES.SMALL),
  widget(DASHBOARD_WIDGET_IDS.CERTIFICATES, 4, DASHBOARD_WIDGET_SIZES.SMALL),
  widget(DASHBOARD_WIDGET_IDS.EVENT_CALENDAR, 5, DASHBOARD_WIDGET_SIZES.LARGE),
  widget(DASHBOARD_WIDGET_IDS.AI_MENTOR_PRACTICE, 6, DASHBOARD_WIDGET_SIZES.MEDIUM),
];

export const CONTENT_CREATOR_DEFAULT_LAYOUT = ADMIN_DEFAULT_LAYOUT;

export const TRAINER_DEFAULT_LAYOUT: DashboardLayoutWidget[] = [
  widget(DASHBOARD_WIDGET_IDS.EVENT_CALENDAR, 1, DASHBOARD_WIDGET_SIZES.LARGE),
];

export const DEFAULT_LAYOUT_BY_SYSTEM_ROLE: Record<SystemRoleSlug, DashboardLayoutWidget[]> = {
  [SYSTEM_ROLE_SLUGS.ADMIN]: ADMIN_DEFAULT_LAYOUT,
  [SYSTEM_ROLE_SLUGS.STUDENT]: STUDENT_DEFAULT_LAYOUT,
  [SYSTEM_ROLE_SLUGS.CONTENT_CREATOR]: CONTENT_CREATOR_DEFAULT_LAYOUT,
  [SYSTEM_ROLE_SLUGS.TRAINER]: TRAINER_DEFAULT_LAYOUT,
};
