export const LEARNING_PATH_ERRORS = {
  MISSING_PERMISSION: "auth.error.missingPermission",
  NOT_FOUND: "learningPathView.toast.notFoundError",
  CREATE_FAILED: "learningPathView.toast.createError",
  UPDATE_FAILED: "learningPathView.toast.updateError",
  UPDATE_MISSING_LANGUAGE: "learningPathView.toast.updateMissingLanguage",
  LANGUAGE_NOT_SUPPORTED: "learningPathView.toast.languageNotSupported",
  COURSE_NOT_FOUND: "learningPathView.toast.courseNotFound",
  COURSE_ALREADY_EXISTS: "learningPathView.toast.courseAlreadyExists",
  COURSE_IDS_UNIQUE: "learningPathView.toast.courseIdsMustBeUnique",
  COURSE_IDS_EMPTY: "learningPathView.toast.courseIdsEmpty",
  COURSE_IDS_MISMATCH: "learningPathView.toast.courseIdsMismatch",
  COURSE_LINK_NOT_FOUND: "learningPathView.toast.courseLinkNotFound",
  STUDENT_IDS_EMPTY: "learningPathView.toast.studentIdsEmpty",
  GROUP_IDS_EMPTY: "learningPathView.toast.groupIdsEmpty",
  EXPORT_NO_TARGET_TENANTS: "learningPathExport.error.noTargetTenants",
  EXPORT_LINK_MISSING: "learningPathExport.error.exportLinkMissing",
  EXPORT_COURSE_FAILED: "learningPathExport.error.courseExportFailed",
  EXPORT_TARGET_AUTHOR_MISSING: "learningPathExport.error.targetAuthorMissing",
  EXPORT_JOB_NOT_FOUND: "learningPathExport.error.jobNotFound",
  CERTIFICATE_DISABLED: "learningPathCertificate.error.disabled",
} as const;
