name: Generate Release Changelog

on:
  push:
    tags:
      - v*

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
          fetch-depth: 0

       - name: Setup Go
         uses: actions/setup-go@v5
         with:
          go-version: 1.24.1

       - name: Install git-chglog
         run: go install github.com/git-chglog/git-chglog/cmd/git-chglog@0.15.4
      
       - name: Generate CHANGELOG.md
         run: git-chglog -o CHANGELOG.md

       - name: Commit changelog
         run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: update changelog"
          git push
